create extension if not exists pgcrypto;

create table public.media_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 500),
  artist text not null default 'Catalogue propriétaire',
  album text,
  kind text not null check (kind in ('audio', 'video')),
  origin text not null check (origin in ('local', 'direct', 'youtube-export', 'facebook-export', 'spotify-catalog')),
  mime_type text not null,
  source_url text,
  storage_path text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  duration_seconds numeric check (duration_seconds is null or duration_seconds >= 0),
  bpm numeric check (bpm is null or bpm between 1 and 400),
  musical_key text,
  genre text,
  favorite boolean not null default false,
  downloaded boolean not null default false,
  rights_confirmed boolean not null default false,
  play_count integer not null default 0 check (play_count >= 0),
  last_played_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint media_items_location_check check (source_url is not null or storage_path is not null or origin = 'local')
);

create table public.playlists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 200),
  description text,
  cover_path text,
  is_smart boolean not null default false,
  smart_rules jsonb not null default '{}'::jsonb,
  is_shared boolean not null default false,
  share_token uuid not null default gen_random_uuid() unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.playlist_items (
  playlist_id uuid not null references public.playlists(id) on delete cascade,
  media_id uuid not null references public.media_items(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  position integer not null check (position >= 0),
  added_at timestamptz not null default now(),
  primary key (playlist_id, media_id)
);

create table public.listening_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_id uuid not null references public.media_items(id) on delete cascade,
  played_at timestamptz not null default now(),
  progress_seconds numeric not null default 0 check (progress_seconds >= 0),
  completed boolean not null default false
);

create index media_items_user_created_idx on public.media_items(user_id, created_at desc);
create index media_items_user_favorite_idx on public.media_items(user_id, favorite) where favorite = true;
create index playlists_user_created_idx on public.playlists(user_id, created_at desc);
create index playlist_items_user_playlist_position_idx on public.playlist_items(user_id, playlist_id, position);
create index listening_history_user_played_idx on public.listening_history(user_id, played_at desc);

alter table public.media_items enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_items enable row level security;
alter table public.listening_history enable row level security;

revoke all on public.media_items, public.playlists, public.playlist_items, public.listening_history from anon;
grant select, insert, update, delete on public.media_items, public.playlists, public.playlist_items, public.listening_history to authenticated;
grant usage, select on sequence public.listening_history_id_seq to authenticated;

create policy "Owners read media" on public.media_items for select to authenticated
using ((select auth.uid()) = user_id);
create policy "Owners insert media" on public.media_items for insert to authenticated
with check ((select auth.uid()) = user_id and rights_confirmed);
create policy "Owners update media" on public.media_items for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id and rights_confirmed);
create policy "Owners delete media" on public.media_items for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "Owners read playlists" on public.playlists for select to authenticated
using ((select auth.uid()) = user_id);
create policy "Owners insert playlists" on public.playlists for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy "Owners update playlists" on public.playlists for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy "Owners delete playlists" on public.playlists for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "Owners read playlist items" on public.playlist_items for select to authenticated
using ((select auth.uid()) = user_id);
create policy "Owners insert playlist items" on public.playlist_items for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (select 1 from public.playlists p where p.id = playlist_id and p.user_id = (select auth.uid()))
  and exists (select 1 from public.media_items m where m.id = media_id and m.user_id = (select auth.uid()))
);
create policy "Owners update playlist items" on public.playlist_items for update to authenticated
using ((select auth.uid()) = user_id)
with check (
  (select auth.uid()) = user_id
  and exists (select 1 from public.playlists p where p.id = playlist_id and p.user_id = (select auth.uid()))
  and exists (select 1 from public.media_items m where m.id = media_id and m.user_id = (select auth.uid()))
);
create policy "Owners delete playlist items" on public.playlist_items for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "Owners read history" on public.listening_history for select to authenticated
using ((select auth.uid()) = user_id);
create policy "Owners insert history" on public.listening_history for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (select 1 from public.media_items m where m.id = media_id and m.user_id = (select auth.uid()))
);
create policy "Owners update history" on public.listening_history for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy "Owners delete history" on public.listening_history for delete to authenticated
using ((select auth.uid()) = user_id);
